### ISSUE TITLE
Cordova storage options

### ISSUE THREAD

**Issue by russbiggs** [sharedstreets/curb-wheel-archive#129]
By moving the services off the pi we'll need to have a strategy on how to store data on the user's device. Cordova allows access to some browser storage APIs like LocalStorage and IndexedDB but these may have some limitations particularly on iOS. Its not 100% clear is IndexedDB is supported in Cordova on iOS (some _old_ sources say it is not supported, some newer source hint at it being supported). Also iOS will clear any browser based storage if the device runs low on storage, seemingly without warning.

I propose we can use a hybrid approach:
* Utilize SQLite for persisting survey data 
* Use IndexedDB for caching tiles, intermediate survey data - this will allow for cases where the internet connection drops

**Comment by emilyeros** [comment]
@russbiggs is this still relevant or can I close it?
