### ISSUE TITLE
Oct 26 punchlist (targets for alpha version so we can go map)

### ISSUE THREAD

**Issue by emilyeros** [sharedstreets/curb-wheel-archive#138]
## Needed before we can map SF and release to testing cohort:

- [ ] iOS app release (will need to test this out and prob make a few tweaks)
- [ ] S3 upload workflow, so that users can locate and access uploads
- [x] Data model tweaks. For each point captured / feature surveyed, include: `featureID`, `surveyID`, `spanID`, timestamp, IMEI. These will be included in the export as objectIDs for the regs/points. 
- [ ] Digitizer: address export bug, add featureID to the UI, enable user to sort by label or by featureID, add spanId and position Id to CurbLR export and add all the IDs listed above ^ to points export
- [x] Buffer fire hydrant points on backend and pass that span to the digitizer. Radius = 4.6 metres (~15 feet). This is the most common rule in the US/Canada, though there were some outliers with a 10-ft radius. (For reference, cities checked: SF, Portland*, Seattle, NYC, DC*, Baltimore, Denver*, St Louis, Minneapolis*, Vancouver, Toronto*, Montreal*, Calgary, Cincinnati*, Austin, Houston, Miami, Raleigh, Boise, Salt Lake City, Las Vegas*, Los Angeles, Atlanta)
- [ ] Put up a hosted version of the digitizer
- [ ] Create new APK with the app changes
- [ ] Testing: general check from start to finish, try uploading a large amount of images, check selection ability in UI when mapping the same street multiple times
- [ ] Overhaul docs with non-technical audience in mind

**Comment by russbiggs** [comment]
Moved to active curb-whell repo
